jobs:
  job_1:
    grace_seconds: 180
    name: job_1
    notify:
    - default
    platform: linux cron
    realert_interval: every 8 hours
    schedule: '*/15 * * * *'
    timezone: Japan
  test-job-3:
    environments:
    - production
    grace_seconds: 60
    group: dev
    name: test-job-3
    notify:
    - default
    platform: linux cron
    realert_interval: every 8 hours
    schedule: '*/15 * * * *'
    timezone: Japan
  test-job-4:
    environments:
    - production
    grace_seconds: 60
    name: test-job-4
    notify:
    - default
    platform: linux cron
    realert_interval: every 8 hours
    schedule: '*/15 * * * *'
    timezone: Japan
  test-job-5:
    environments:
    - production
    grace_seconds: 60
    name: test-job-5
    notify:
    - default
    platform: linux cron
    realert_interval: every 8 hours
    schedule: '*/15 * * * *'
    timezone: Japan
  # test-job-2:
  #   environments:
  #   - production
  #   grace_seconds: 60
  #   name: test-job-2
  #   notify:
  #   - default
  #   platform: linux cron
  #   realert_interval: every 8 hours
  #   schedule: '*/15 * * * *'
  #   timezone: Japan